service: business-logic

plugins:
  - serverless-latest-layer-plugin # activate plugin

provider:
  name: aws
  runtime: nodejs10.x # programming language & version
  stage: ${opt:stage, 'dev'} # current stage dev/test/prod
  region: ${opt:region, 'eu-central-1'} # current AWS Region

custom:
  config: ${file(../ouputs.json)} # load json
  ACCOUNT_ID: ${self:custom.config.account_id} #reference of the id 

functions:
  helloWorld:
    handler: handler.hello
    events:
      - http:
          path: helloWorld
          method: get
          cors: true
    environment:
      NODE_PATH: "./:/opt/node_modules" # Important otherwise node_modules imported can not be found
    layers:
      - arn:aws:lambda:${opt:region, 'eu-central-1'}:${self:custom.ACCOUNT_ID}:layer:${opt:stage, 'dev'}-base-layer:latest #replace this with arn from layer, or create terraform variable with layer ARN
